
set(FILES
    Include/Conversation/AvailabilityBus.h
    Include/Conversation/ConversationAsset.h
    Include/Conversation/ConversationBus.h
    Include/Conversation/DialogueComponent.h
    Include/Conversation/DialogueComponentBus.h
    Include/Conversation/DialogueData.h
    Include/Conversation/DialogueNodes.h
    Include/Conversation/DialogueScript.h
    Source/AddDialogueNodeable.h
    Source/AddDialogueNodeable.cpp
    Source/AddDialogueNodeable.ScriptCanvasNodeable.xml
    Source/AvailabilityBus.cpp
    Source/ConversationAsset.cpp
    Source/ConversationModuleInterface.h
    Source/ConversationSystemComponent.cpp
    Source/ConversationSystemComponent.h
    Source/DialogueComponent.cpp
    Source/DialogueComponentBus.cpp
    Source/DialogueData.cpp
    Source/DialogueLibrary.h
    Source/DialogueLibrary.cpp
    Source/DialogueNodes.cpp
)
