-- ConversationGraphName condition

--require("conversation.core")

-- BOP_GENERATED_INCLUDES_BEGIN

-- BOP_GENERATED_INCLUDES_END

-- BOP_GENERATED_FUNCTIONS_BEGIN

-- BOP_GENERATED_FUNCTIONS_END

-- BOP_GENERATED_INSTRUCTIONS_BEGIN

-- BOP_GENERATED_INSTRUCTIONS_END
