---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dinkleberg.
--- DateTime: 10/28/24 5:46 PM
---

local Script = {
    Properties = {
        EnableDebug = { default = false },
        PlayerEntityId = { default = EntityId() }
    }
}

function Script:OnActivate()
    self.dialogueComponentNotificationHandler = DialogueComponentNotificationBus.Connect(self, self.entityId)
    Debug.Log("CAMERA_CONTROLLER ON ACTIVATE")
end

function Script:OnDeactivate()
    if self.dialogueComponentNotificationHandler ~= nil then
        self.dialogueComponentNotificationHandler:Disconnect()
        self.dialogueComponentNotificationHandler = nil
    end
end

function Script:OnDialogue(dialogue, availableResponses)
    Debug.Log("FUCK FUCK FUCK FUCK FUCK")
    Debug.Log("In on dialogue of camera_controller")
    if dialogue.Speaker == "owner" then
        local hasCamTargetTag = TagComponentRequestBus.Event.HasTag(self.entityId, GetConversationCameraTargetTag())
        if hasCamTargetTag == false then
            TagComponentRequestBus.Event.AddTag(self.entityId, GetConversationCameraTargetTag())
            Debug.Log("camera_controller.lua/OnDialogue: Added camera tag to owner")
        end
    else
        TagComponentRequestBus.Event.AddTag(self.Properties.PlayerEntityId, GetConversationCameraTargetTag())
        Debug.Log("camera_controller.lua/OnDialogue: Added camera tag to player")
    end
end

return Script